### ISSUE TITLE
How to configure JMX-JBOSS in Datadog

### ISSUE THREAD

**Issue by snithyashree** [DataDog/jmxfetch#120]
Hi,

I have configured JMX in jboss to get the metrics in datadog.But i am unable to get the metrics.Will you pls give the steps to configure the jboss in datadog

**Comment by olivielpeau** [comment]
Hi @snithyashree, have you had a look at the section of our docs on monitoring JBoss applications?
http://docs.datadoghq.com/integrations/java/#monitoring-jbosswildfly-applications

**Comment by yannmh** [comment]
@snithyashree I am closing this issue since we haven't heard back from you. 

Please don't hesitate to re-open if needed or reach our support team.
