### ISSUE TITLE
No support for type: java.util.map

### ISSUE THREAD

**Issue by KParzival** [DataDog/jmxfetch#125]
Migrating a bunch of hosts from current monitoring solution to Datadog, discovered that this JMX type was not supported by Datadog.

Example output from JTerm:
```
#mbean = sme:name=ActiveCampaignStats:
CampaignCount = {
  Europe = 4563;
  Asia = 1128;
  All = 82134;
 };
$>
```

Which in JConsole might look something like:
```
AttributeName:        AttributeValue:
=======================================
CampaignCount         {Europe=4563,Asia=1128,All=82134}
```

**Comment by yannmh** [comment]
Hey @KParzival,

Maps are actually supported: use the syntax `$variable.$key` in the list of attributes to grab the desired parameter. Here is an example: https://github.com/DataDog/jmxfetch/blob/master/src/main/resources/jmx-2.yaml 

Please let me know if that helps.

**Comment by KParzival** [comment]
I tried that exact syntax, it doesn't work.
I then worked directly with a DD Support person, when running: `/etc/init.d/datadog-agent jmx list_everything`, the Beans that have only java.util.map types, don't even show up as being grabbed by JMXFetch, and java.util.map is not in the list of supported types listed here: https://github.com/DataDog/jmxfetch/blob/master/src/main/java/org/datadog/jmxfetch/Instance.java#L23-L28

**Comment by yannmh** [comment]
Thanks for the details @KParzival,

Could you send us a [flare](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support-using-flare) please? It's likely a small code change and this would be very helpful.

**Comment by KParzival** [comment]
Hi @yannmh,
Already sent a flare today when working on a case with Alex/Grant.

Case# 82354

**Comment by yannmh** [comment]
Thanks @KParzival. We found the issue and are working on a fix for the upcoming agent release.
