### ISSUE TITLE
Error parsing list of tags

### ISSUE THREAD

**Issue by masci** [DataDog/jmxfetch#131]
JMX-fetch only expects tags to be listed as a map in the YAML file but there are cases when they might be arrays. One example is the output of the template parsing in Service Discovery, see https://github.com/DataDog/dd-agent/blob/69d58afeea2126ab2a7e1e1efba6f3cbdafc7f33/utils/service_discovery/sd_docker_backend.py#L410-#L420

In such cases the error looks like this:
```
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.LinkedHashMap
	at org.datadog.jmxfetch.Instance.<init>(Instance.java:71)
	at org.datadog.jmxfetch.App.init(App.java:485)
	at org.datadog.jmxfetch.App.start(App.java:241)
	at org.datadog.jmxfetch.App.main(App.java:122)
```

We should fix JMX-fetch so it can accept tags in both formats.

**Comment by yannmh** [comment]
Thanks for the details @masci. A fix is coming.
