### ISSUE TITLE
Be more flexible on configuration

### ISSUE THREAD

**Issue by remh** [DataDog/jmxfetch#20]
- Support wildcards
- Support list of filters instead of simple filters.
- ...

Use case:
I want to exclude a few column families for the cassandra integration.

**Comment by reikje** [comment]
Would be nice to support lists not only for attributes, i.e. 
```
- include:
 domain: org.apache.cassandra.metrics
 type: ClientRequest
 scope: 
   – Write
   – Read
 attribute: 
   – Max
   – Mean
   – 95thPercentile
```
