### ISSUE TITLE
Is there any approach to capture process id as metric's label

### ISSUE THREAD

**Issue by qiansheng91** [DataDog/jmxfetch#494]
I deploy multiple java processor in one machine, and I want to statistic all processes list in this machine. so I want to capture process id as metric's label

**Comment by carlosroman** [comment]
Apologies, but I am not sure I understand what you are aiming to do. Are you using the [Datadog Agent](https://docs.datadoghq.com/agent/), if so maybe the [Live Processes](https://docs.datadoghq.com/infrastructure/process/?tab=linuxwindows) is what you are looking for?
