### ISSUE TITLE
Question: When is the next release?

### ISSUE THREAD

**Issue by jamesbassett** [DataDog/jmxfetch#517]
We were updating some of our apps to JDK21 with the new generational ZGC garbage collector, but noticed that Datadog wasn't reporting the GC times correctly.

We believe it's because the datadog agent doesn't have the following change from jmxfetch:
https://github.com/DataDog/jmxfetch/pull/509

Is it correct to say this wouldn't be available until jmxfetch creates a new release, and if so when do you plan on creating the next release?

**Comment by carlosroman** [comment]
Hi @jamesbassett. Looking at getting this into version `7.54` of the Datadog Agent which will be out in seven weeks or so. Will create a release of `0.49.1` and publish that to Maven Central if you want to use if before that release of the Agent.

**Comment by carlosroman** [comment]
So `7.54.0` is being QA'ed and will be out in a few weeks, (currently on RC2, https://github.com/DataDog/datadog-agent/tree/7.54.0-rc.2).
