### ISSUE TITLE
100% IO Wait

### ISSUE THREAD

**Issue by sschepens** [DataDog/jmxfetch#69]
I don't know why, every a few hours, jmxfetch eats up all of the Disk IO.
It also lasts for several minutes and after that the process dies.

![screenshot from 2015-08-21 16-37-37](https://cloud.githubusercontent.com/assets/3072509/9417584/e119a620-4823-11e5-8a5c-4972da4a9f81.png)

![screenshot from 2015-08-21 16-37-38](https://cloud.githubusercontent.com/assets/3072509/9417587/e3b46424-4823-11e5-8509-fbc01f687ecf.png)

**Comment by yannmh** [comment]
Hi @sschepens,

Sorry to hear that you are experiencing issues with JMXFetch. Would you mind to reach out to support AT datadoghq.com with those details and a ['flare'](https://github.com/DataDog/dd-agent/wiki/Send-logs-to-support) archive please ? We'll be able to follow up quicker and more efficiently !
